### ISSUE TITLE
Problems i faced for now

### ISSUE THREAD

**Issue by zahodinikola** [zahodinikola/copy#1]
1. I am experiencing problems with exact positioning elements on a window
2. For now i didn`t pay much attention to elegant coding regarding styling
3. I push changes from Visual Studio Code. Unfortunately i can`t do it to other branch then master.
I did branch try-styling, but anyway changes via VSCode were made in master.
* Now i have one repository related to this project on GitHub and two on local machine.
If i write markup in VSCode, then push it to GitHub and then call through SourceTree to another directory on my computer. I do it to get familiar with functionality

**Comment by humanier** [comment]
1. We can touch this question tomorrow.
2. Do not worry too much. I put my suggestions regarding this in https://github.com/zahodinikola/copy/issues/4
3. We need to look at this together sharing screens. We can try tomorrow.

**Comment by humanier** [comment]
I think we covered questions from this issue. I am closing it for now.
